version: '3'

services:
  db:
    image: postgres:9
    expose:
      - '5432'
    environment:
      - POSTGRES_USER=django_home_app
      - POSTGRES_PASSWORD=P@ssw0rd
      - POSTGRES_DB=centennial_db
    volumes:
      - postgres-data:/var/lib/postgresql/data
  web:
    image: centennial
    command: python manage.py runserver 0.0.0.0:8000
    ports:
      - '8000'
    expose:
      - '8000'
    depends_on:
      - db

volumes:
  postgres-data:
