version: '3'

services:
  db:
    image: postgres:9
    expose:
      - '5432'
    environment:
      - POSTGRES_USER=django_home_app
      - POSTGRES_PASSWORD=P@ssw0rd
      - POSTGRES_DB=centennial_db
    volumes:
      - postgres-data:/var/lib/postgresql/data
    networks:
      - centennial-network

  web:
    image: johnmcdevitt/centennial-dev:${DEV_VERSION}
    command: python manage.py runserver 0.0.0.0:8000
    ports:
      - '8000'
    expose:
      - '8000'
    depends_on:
      - db
    volumes:
      - centennial-media:/media
    networks:
      - centennial-network

  nginx:
    image: mynginx
    ports:
      - "80:80"
    container_name: centennial-nginx
    depends_on:
      - web
    networks:
      - centennial-network

volumes:
  postgres-data:
  centennial-media:

networks:
  centennial-network: