version: '3'

services:
  db:
    image: postgres:9
    expose:
      - '5432'
    environment:
      - POSTGRES_USER=django_home_app
      - POSTGRES_PASSWORD=P@ssw0rd
      - POSTGRES_DB=centennial_db
    volumes:
      - pg-data:/var/lib/postgresql/data
    networks:
      - centennial-network

  web:
    image: johnmcdevitt/centennial-dev:${DEV_VERSION}
    command: python manage.py runserver 0.0.0.0:8000
    ports:
      - '8000'
    expose:
      - '8000'
    volumes:
      - centennial-media:/media
    depends_on:
      - db
    networks:
      - centennial-network

  nginx:
    image: johnmcdevitt/nginx:centennial_0.2
    ports:
      - ${NGINX_PORTS}
    depends_on:
      - web
    networks:
      - centennial-network

volumes:
  pg-data:
  centennial-media:

networks:
  centennial-network:
