# Generated by Django 2.0.3 on 2018-04-06 22:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Floors',
            fields=[
                ('floorid', models.AutoField(primary_key=True, serialize=False)),
                ('floorlevel', models.SmallIntegerField()),
                ('floorname', models.CharField(max_length=20, unique=True)),
            ],
        ),
    ]
