# Generated by Django 2.0.3 on 2018-04-07 00:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('house', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Floors',
            new_name='Floor',
        ),
    ]
