# Generated by Django 2.0.3 on 2018-04-07 11:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('house', '0002_auto_20180407_0024'),
    ]

    operations = [
        migrations.CreateModel(
            name='Room',
            fields=[
                ('roomid', models.AutoField(primary_key=True, serialize=False)),
                ('roomname', models.CharField(max_length=20, unique=True)),
                ('floorname', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='house.Floor')),
            ],
        ),
    ]
