# Generated by Django 2.1.5 on 2019-02-21 23:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cards', '0002_card_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='CardType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cardtype', models.CharField(max_length=30, unique=True)),
                ('color', models.CharField(max_length=6)),
            ],
        ),
        migrations.AlterField(
            model_name='card',
            name='status',
            field=models.CharField(choices=[('100', 'Backlog'), ('200', 'To do'), ('300', 'In progress'), ('400', 'Review'), ('500', 'Done')], default='100', max_length=3),
        ),
        migrations.AddField(
            model_name='card',
            name='type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='cards.CardType'),
        ),
    ]
