# Generated by Django 2.1.5 on 2019-03-01 22:47

import cards.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cards', '0003_auto_20190221_1850'),
    ]

    operations = [
        migrations.AddField(
            model_name='card',
            name='order',
            field=models.BigIntegerField(null=True, unique=True),
        ),
    ]
