# Generated by Django 2.1.5 on 2019-03-01 23:00

import cards.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cards', '0005_auto_20190301_1751'),
    ]

    operations = [
        migrations.AlterField(
            model_name='card',
            name='order',
            field=models.PositiveIntegerField(default=cards.models.order_default_value, null=True, unique=True),
        ),
    ]
