# Generated by Django 2.1.7 on 2019-03-20 22:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cards', '0006_auto_20190301_1800'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cardtype',
            name='cardtype',
            field=models.CharField(max_length=30, unique=True, verbose_name='Type'),
        ),
        migrations.AlterField(
            model_name='cardtype',
            name='color',
            field=models.CharField(max_length=6, unique=True),
        ),
    ]
