# Generated by Django 2.1.7 on 2019-03-24 22:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cards', '0007_auto_20190320_1750'),
    ]

    operations = [
        migrations.AddField(
            model_name='cardtype',
            name='icon',
            field=models.CharField(default='far fa-question-circle', help_text='Font awesome class', max_length=40),
        ),
    ]
