# Generated by Django 2.1.7 on 2019-04-26 02:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cards', '0010_cardtasks_done'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='CardTasks',
            new_name='CardTask',
        ),
    ]
